= Introduction

== openEHR Process and Planning Artefacts

openEHR provides specifications for various models and languages to address the area of process and guideline-driven healthcare. These are as follows:

* A _plan_ definition formalism: the {openehr_task_planning}[openEHR Task Planning specification^];
* A _logic / rules_ definition language: the {openehr_dlm}[openEHR Decision Logic Module (DLM) specification^];
* An _expression language_, which forms the basis for writing expressions and rules, defined by the {openehr_bmm}[openEHR Basic Meta-Model ^];
* A specification for a _subject proxy service_, which forms the bridge between concrete data sources and plans and decision logic as consumers: the {openehr_subject_proxy}[openEHR Subject Proxy specification^].

Together these enable the authoring of guidelines (GDL3 format), executable care plans and in-application active forms. There is also an existing guideline language, {openehr_cds_gdl2}[Guideline Definition Language 2 (GDL2)^], which defines an earlier self-standing guideline format, and which can be replaced by the DLM format GDL3 guideline.

== Prior Art

openEHR DLM language may be compared to other languages developed in the health arena for expressing 'medical logic', including {hl7v3_arden}[HL7 Arden Syntax^], Guideline Interchange Format cite:[GLIF], ProForma cite:[SuttonFox2003], as well as Decision Languages such as {hl7v3_gello}[HL7 Gello^]. These languages were not directly used, for various reasons including:

* they do not support any distinction of ontic versus epistemic variables;
* none have an easily extensible value referencing mechanism;
* some are too procedural (Arden, GLIF);
* current versions of some of these languages have been made specific to the HL7v3 RIM, a particular (and obsolete) model of health information designed for message representation (GLIF 3.x, GELLO);
* none of them have a clear separation of the semantics of process representation, decision logic, proxy data and data access;
* the maintenance and support is unclear and/or limited.

Nevertheless, various elements of Arden provided useful inspiration for the formalism described here. The Data Access Binding described here may be understood as a solution to the so-called 'curly braces problem' of Arden cite:[Samwald_arden_2012], i.e. the need to be able to bind rule logic to real-world variables.

Much of the formal semantics of the DLM formalism comes from experience with GDL2 deployments.

== Other Standards

Other relevant formalisms include the OMG {omg_bpmn}[BPMN^], {omg_cmmn}[CMMN^] and {omg_dmn}[DMN^] standards, and the {hl7_cql}[HL7 CQL standard^]. The former group of standards are starting (as of 2020) to find use in the healthcare arena, having been developed for other industries including process control, logistics and insurance, and will require further development and integration for use in healthcare. The HL7 CQL standard addresses some of the same issues as openEHR DLM/EL.
