= Subject Datasets

Within a process-driven clinical computing environment, the Subject Proxy Object (SPO) is the interface between the plan and guideline components on the one hand, and patient data on the other. The logical SPO component is shown in <<conceptual_framework>> in the context of the related components (blue box, centre left).


== References Ranges and Event Generation

Many variables including vital signs and lab analytes have various associated reference ranges. These ranges can be stated within a Subject Proxy variable definition to achieve two useful goals:

* providing formally named ranges for use within rules;
* enabling event notifications to be generated when the live value crosses a threshold (e.g. enters 'critical low').

The following provides an example definition including reference ranges.

----
state
    // Glomerular filtration rate
    gfr: Quantity
        currency = 24h
        ranges = 
            [normal]:      |>20 mL/min|,
            [low]:         |10 - 20 mL/min|,
            [very_low]:    |<10 mL/min|
----

Given the above definition, it is relatively easy to engineer the capability for an SPO to generate notifications for when the `gfr` value crosses the `low` and `very_low` threshold limits. This means that the SPO acts not only as a source of reified subject variables but also as a real-time generator of event notifications relating to their trajectories as well.

