= Overview

== Conceptual Model

The openEHR Decision Support Language (DSL) and Decision Support Language Model (DSLM) define a formalism for expressing decision logic used in healthcare and biomedical research. Decision logic usually sits within a larger environment of plans, workflows and also data sources such as the EHR. The following diagram illustrates the artefacts covered by this specification within the wider computational context.

[.text-center]
.openEHR conceptual framework for computable care pathways
image::{common_diagrams_uri}/conceptual_framework_overview.svg[id=conceptual_framework_overview, align="center"]

In the above, the top part illustrates process and plan definitions, of which the _care pathway_ is a specific example in clinical medicine. In openEHR these are expressed as Work Plans, defined by the {openehr_task_planning}[openEHR Task Planning model^]. In other environments, OMG BPMN/CMMN representation might be used.

Below the process component, the two components of the decision support framework decribed in this specification are shown:

* *Decision Support Module (DSM)*: modules containing decision functions that generate inferences from input variables representing real world entities being reasoned about;
* *Subject Proxy Object (SPO)*: a definition of state variables and events characterising a real-world entity in a convenient form for use in a DSM.

The remaining component (shown at bottom left) is the _Data Access Binding (DAB)_, which consists of bindings to data sources and repositories, such as patient health records and monitoring devices. Data from these locations is extracted to populate the input variables of a Subject Proxy.

In this environment, the Process Definition component may be understood as a primary user of DSMs and SPOs, providing it respectively with access to real world state (e.g. patient vital signs) and the results of inferencing on such state variables. As a consequence (and unlike BPMN), formal expressions do not appear in process definitions, only references to variables and functions.

The essential characterisation of _decision support logic_ understood in this specification is a function-oriented logic that generates deductive inferences, such as clinical classification of patients (including diagnosis), from input variables representing known facts about the patient. These include results obtained from real world observation, measurement, imaging etc, as well as previous confirmed diagnosis and records of previous procedures. This specification considers decision support logic to consist of _definitions_, as well as various logical elements, including:

* _conditions_: Boolean-valued simple rules;
* _rules_: rules generating non-Boolean values;
* _rule-sets_: collections of rules that operate on a common set of input variables to generate a common set of output values.

Rule-sets may come in various forms, including the _decision table_, a common way of documenting a set of related rules using a 2-dimensional table.

Rules typically contain _conditions_ i.e. Boolean-returning expressions such as `_heart_rate_ >= 120 /min and _heart_rhythm_ = |irregular|` that are used as criteria for choosing decision paths within a function. In many domains, including healthcare, such conditions are often determined by long-term, evidence-based research, and may be well-known within a domain. For example, the innocuous-looking condition `_blood_glucose_[2h post 75g glucose challenge] > 6.5 mmol/ml` is the diagnostic standard for type I diabetes.

Conditions, rules, rule-sets and other inference-generating structures that may include them constitute fragments of knowledge that need to be able to be authored and change-managed independently from contexts that use them, rather than being directly written into (say) if/then/else logic chains as a programmer would typically do. This specification accordingly provides a representational form for such logic, along with artefacts that connect them to data access services (e.g. EHR) and also enable them to be invoked by user contexts (e.g. workflow engines).

Decision support logic necessarily requires a way of defining and expressing its _input variables_. This is not just a question of creating typed variables, but one of semantics. The 'variables' used in rules represent an _ontic_ view of the subject, that is, a true description of its state in reality. For example, a rule for inferring atrial fibrillation and other forms of arrhythmia may refer to the input variables `_heart_rate_` and `_heart_rhythm_`. The meaning of these variables is that they represent the real heart rate and rhythm of the patient, rather than being just any heart rate, e.g. from a measurement 3 years ago. Similarly, a variable `_is_type1_diabetic_` represents a proposition about the patient in reality.

A second requirement of rule variables is that they are close to the language of the domain, for example `_is_type1_diabetic_` and `_has_family_history_of_breast_cancer_` are things a clinical professional instantly understands. Semantically, they tend to be highly precoordinated forms of more technical representations, e.g. `problem_list.contains (type = 73211009|diabetes mellitus|, status=confirmed)`.

In order to support the definition of such variables, a connection is of course needed to the technical representation of data found within EHRs, documents, lab messages, real-time devices and other sources. These latter constitute the _epistemic_ knowledge base for extracting the ontic view. They also tend to be highly variable, due to different concrete standards, products and databases. The ability to write decision logic in a natural yet computable way - independent of specific access methods and type systems - thus requires support for various levels of representation above the purely technical data items and APIs found in healthcare information systems. The Subject Proxy component in the scheme illustrated above constitutes the top-most reification of underlying data in the form of domain-comprehensible ontic variables.

== Prior Art

openEHR DSL may be compared to other languages developed in the health arena for expressing 'medical logic', including {hl7v3_arden}[HL7 Arden Syntax^], Guideline Interchange Format cite:[GLIF], ProForma cite:[SuttonFox2003], as well as decision support languages such as {hl7v3_gello}[HL7 Gello^]. These languages were not directly used, for various reasons including:

* they do not support any distinction of ontic versus epistemic variables;
* none have an easily extensible value referencing mechanism;
* some are too procedural (Arden, GLIF);
* current versions of some of these languages have been made specific to the HL7v3 RIM, a particular (and obsolete) model of health information designed for message representation (GLIF 3.x, GELLO);
* none of them have a clear separation of the semantics of process representation, decision logic, proxy data and data access;
* the maintenance and support is unclear and/or limited.

Nevertheless, various elements of Arden provided useful inspiration for the formalism described here. The Data Access Binding described here may be understood as a solution to the so-called 'curly braces problem' of Arden cite:[Samwald_arden_2012], i.e. the need to be able to bind rule logic to real-world variables.

== Other Standards

Other relevant formalisms include the OMG {omg_bpmn}[BPMN^], {omg_cmmn}[CMMN^] and {omg_dmn}[DMN^] standards, and the {hl7_cql}[HL7 CQL standard^]. The former group of standards are starting (as of 2020) to find use in the healthcare arena, having been developed for other industries including process control, logistics and insurance, and will require further development and integration for use in healthcare. The HL7 CQL standard addresses some of the same issues as openEHR DL/EL.
