[[_dlm_model]]
= Decision Logic Module (DLM) Model

== Overview

The `org.openehr.proc.decision_language.dlm` package defines the Decision Logic Module (DLM) structure, a specialisation of the class meta-type from the {openehr_bmm}[openEHR BMM^].

The structure of the `proc.decision_language` packages is shown below.

[.text-center]
.`proc.decision_language` Package strucure
image::{uml_diagrams_uri}/PROC-decision_language-packages.svg[id=dl_packages, align="center", width="50%"]

The packages are described below.

== Decision Logic Module Package

The top-level construct of the DLM is the `DECISION_LOGIC_MODULE` meta-class, representing a standalone Decision Logic Module. It is shown below.

[.text-center]
.`proc.decision_language.dlm` Package
image::{uml_diagrams_uri}/PROC-decision_language.dlm.svg[id=dl_dlm, align="center"]

[.tbd]
TBD: to be continued. 

=== Class Descriptions

include::{uml_export_dir}/classes/decision_logic_module.adoc[leveloffset=+1]]

include::{uml_export_dir}/classes/dlm_reference_section.adoc[leveloffset=+1]]

include::{uml_export_dir}/classes/dlm_input_section.adoc[leveloffset=+1]]
include::{uml_export_dir}/classes/tracked_variable.adoc[leveloffset=+1]]
include::{uml_export_dir}/classes/range_def.adoc[leveloffset=+1]]

include::{uml_export_dir}/classes/dlm_rules_section.adoc[leveloffset=+1]]
include::{uml_export_dir}/classes/dlm_rule.adoc[leveloffset=+1]]

