= Preface

== Purpose

This document specifies the openEHR Decision Model (DM) and an abstract syntax, denoted the openEHR Decision Language (openEHR DL). The DOM defines the semantics of a first order predicate style logic that can be used to write clinical Decision Logic Models (DLMs).

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* Solution vendors.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview^].

Releated documents include:

* The {openehr_am_aom2}[Archetype Object Model 2 (AOM2)^], Assertions section.
* The {openehr_cds_gdl}[Guideline Definition Language (GDL)^].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_decision_language}[{openehr_decision_language}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant {openehr_its_component}[openEHR Implementation Technology Specification(s) (ITSs)^], such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.

