= Representation Scheme

== Overview

The general approach to representation for Decision Logic Modules (DLMs) and Proxy Objects (POs) is to support two forms. The first is an optional high-level language form called Decision Logic Language (DLL) suitable for domain specialist authors, which abstracts away detail typically required for a programming language, and also provides some higher level abstractions, such as complex type operators, temporal logic and so on. DLL texts are assumed to be written by hand (possibly with the aid of a syntax mode for typical editors) or a light-weight UI tool.

The second form is an expression in a standard programming language which is either generated from the first form by a cross-compilation process, or directly generated by a more sophisticated UI tool. This direct expression will be significantly more complex, because it encompasses not just the decision logic and proxy definitions, but the ability to compute recommendations (i.e. decision proposals), reasoning chains and other advanced functionality requiring transparent access to the logic structures of a DLM.

The two types of artefacts are shown below.

[.text-center]
.Artefact scheme
image::{diagrams_uri}/artefact_scheme.svg[id=artefact_scheme, align="center"]

== Decision Logic Language

The Decision Logic Language is a high-level programming language in which modules containing the following elements may be written:

* _definitions_ - domain constants;
* _conditions_ - Boolean-returning domain-specified criteria;
* _rules_ - domain-specified rules structures based on condition/action structures, which may return any type.

An example of a basic formalism supporting these concepts is shown below.

----
module 
    Cardiology_basic

data_source
    Patient: HeartPatient

definitions
    Afib_heart_rate: DvQuantity = 120 /min
    High_heart_rate: DvQuantity = 100 /min

conditions
    has_atrial_fibrillation:
        Patient.heart_rhythm = |erratic|286761003 and 
            Patient.heart_rate >= Afib_heart_rate

    has_tachycardia:
        Patient.heart_rate >= High_heart_rate and 
              Patient.exertion = |at rest|263678003

rules
    heart_assessment: DvCodedText {
        condition has_atrial_fibrillation
            Result <- |atrial fibrillation|49436004

        condition has_tachycardia
            Result <- |tachycardia|11092001

        else 
            Result <- |normal|76863003
    }
----

