=== CHOICE_GROUP Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_CHOICE_GROUP (abstract)_*

h|*Description*
2+a|Abstract precursor of root node of any decision structure. All such structures are instances of a Task Group in parallel mode, with XOR (single path) concurrency logic.

h|*Inherit*
2+|`TASK_GROUP`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*override_type*: `OVERRIDE_TYPE`
a|Indicates kind of user override that would be accepted at runtime. If set to a value other than `prohibited`, user interaction is assumed, and runtime processing must enter a

h|*0..1*
|*timeout*: `TIMER_WAIT`
a|Timeout handler to use if `CHOICE_GROUP` blocks unexpectedly, e.g. due to absent user, unavailable external data item.

h|*0..1 +
(redefined)*
|*members*: `List<CHOICE_BRANCH>`
a|Set of Tasks to perform. Execution order is defined by the `_execution_type_` setting, either sequential or parallel (no order).

h|*Invariants*
2+a|_Inv_parallel_: `execution_type = EXECUTION_TYPE.parallel`

h|
2+a|_Inv_xor_concurrency_: `concurrency_mode = CONCURRENCY_MODE.xor_one_path`
|===
