=== DECISION_MODULE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DECISION_MODULE*

h|*Description*
2+a|A container for a set of statements along with related BMM definitions, meta-data, terminology and bindings.

h|*Inherit*
2+|`AUTHORED_RESOURCE`, `BMM_CLASS`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*proxy_properties*: `List<BMM_PROPERTY>`
a|Properties representing real-world objects, such as the patient state, the patient history (logical EHR) etc.

h|*0..1*
|*definitions*: `List<BMM_CONSTANT>`
a|Constant definitions needed by module.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*create_bmm_class*
a|Generate a `BMM_CLASS` structure in which:

* `_constants_` = `_this.definitions_`;
* `_this.conditions_` are converted to `Boolean`-returning functions with no parameters whose `_body_` is a single assignment statement of the form `Result` = `DL_CONDITION_DEF._definition_`;
* `_this.rules_` are converted to `Boolean`-returning functions with no parameters whose `_body_` consists of the `DL_CONDITION_RULE._body_`.
|===
