=== DECISION_LOGIC_MODULE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DECISION_LOGIC_MODULE*

h|*Description*
2+a|Specialised kind of class that represents a Decision Logic Module (DLM).

h|*Inherit*
2+|`link:/releases/BASE/{proc_release}/resource.html#_authored_resource_class[AUTHORED_RESOURCE^]`, `link:/releases/LANG/{proc_release}/bmm.html#_bmm_simple_class_class[BMM_SIMPLE_CLASS^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*definitions*: `link:/releases/BASE/{proc_release}/foundation_types.html#_list_class[List^]<link:/releases/LANG/{proc_release}/bmm.html#_bmm_constant_class[BMM_CONSTANT^]>`
a|Constant definitions needed by module.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*create_bmm_class*
a|Generate a `BMM_CLASS` structure in which:

* `_constants_` = `_this.definitions_`;
* `_this.conditions_` are converted to `Boolean`-returning functions with no parameters whose `_body_` is a single assignment statement of the form `Result` = `DL_CONDITION_DEF._definition_`;
* `_this.rules_` are converted to `Boolean`-returning functions with no parameters whose `_body_` consists of the `DL_CONDITION_RULE._body_`.
|===
