=== PLAN_ITEM Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_PLAN_ITEM (abstract)_*

h|*Description*
2+a|Parent type of structural Task types that may appear within a Task Plan structure.

h|*Inherit*
2+|`LOCATABLE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*description*: `DV_TEXT`
a|Human-readable form of the task directive.

h|*0..1*
|*repeat_spec*: `TASK_REPEAT`
a|Optional specification of repetitions.

h|*0..1*
|*classification*: `ITEM_STRUCTURE`
a|Archetypable structure for recording classification of Task Groups or Tasks, e.g. business process category, administrative category etc.

h|*0..1*
|*wait_spec*: `TASK_WAIT`
a|Optional wait specification for Plan Item (Task or Group) initiation. If not set, the Plan Item is immediately `available` once execution reaches it. If set, it becomes `available` when any Event in `_events_` occurs.

h|*0..1*
|*review_dataset*: `List<REVIEW_DATASET_SPEC>`
a|Optional data-set to review prior to / as part of performing the Plan element.

h|*0..1*
|*guideline_step*: `String`
a|Optional reference to a step within the `_guideline_` referenced by the current Task Plan (if set) or else the `_care_pathway_` of the Work Plan, which is the basis of this Plan Item, i.e. single Task or Task Group.

The reference may take the form of a plain text section or item name within the referenced guideline, e.g. '"Check heart rate"' or be a URI or path reference, if the guideline has an online machine-representation.

h|*0..1*
|*other_details*: `ITEM_STRUCTURE`
a|Archetypable structure for recording non hard-modelled information.

h|*0..1*
|*reminders*: `REMINDER`
a|One or more wait states that may be used to remind the Task performer to do something based on a Timer or other Event. Will be cancelled by the Task transitioning to a terminal state.
|===
