=== PLAN_ITEM Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_PLAN_ITEM (abstract)_*

h|*Description*
2+a|Parent type of structural Task types that may appear within a Task Plan structure.

h|*Inherit*
2+|`LOCATABLE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*description*: `DV_TEXT`
a|Human-readable form of the task directive.

h|*0..1*
|*repeat_spec*: `TASK_REPEAT`
a|Optional specification of repetitions.

h|*0..1*
|*other_details*: `ITEM_STRUCTURE`
a|Archetypable structure for recording non hard-modelled information.

h|*0..1*
|*wait_spec*: `TASK_WAIT`
a|Optional wait specification for a Task. If not set, the Task is immediately available once execution reaches it. If set, the Task becomes available when an Event linked to the `_wait_spec_` occurs.

h|*0..1*
|*review_dataset*: `List<REVIEW_DATASET_SPEC>`
a|Optional data-set to review prior to / as part of performing the Plan element.

h|*0..1*
|*order_tags*: `List<String>`
a|References to order(s) being created and / or tracked by this Plan item. The value(s) must match `ORDER_REF._order_tag_` values from the list `WORK_PLAN._order_list_`.

Multiple tags are only required if the same Task causes creation of, or tracks, more than one order.
|===
