=== PROXY_SERVICE Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*PROXY_SERVICE*

h|*Description*
2+a|Service that tracks registered subject variables and caches them. Calls to `_register_variable_()` will cause the creation of two things:

* a local cache of time-tagged historical values of the variable;
* an agent or other method of obtaining the variable value from back-end systems.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*register_variable* ( +
subject_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]`, +
plan_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]`, +
def: `<<_sp_variable_def_class,SP_VARIABLE_DEF>>[1]`, +
currency: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^][0..1]` +
)
a|Register a new variable for a subject and plan. The variable definition is given by `_def_`. If `_currency_` is specified, it indicates the oldest value acceptable to maintain the validity of the variable.

h|*1..1*
|*read_boolean_variable* ( +
subject_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]`, +
name: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]` +
): `link:/releases/BASE/{base_release}/base_types.html#_boolean_data_item_class[Boolean_data_item^]`
a|

h|*1..1*
|*read_integer_variable* ( +
subject_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]`, +
name: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]` +
): `link:/releases/BASE/{base_release}/base_types.html#_integer_data_item_class[Integer_data_item^]`
a|

h|*1..1*
|*read_real_variable* ( +
subject_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]`, +
name: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]` +
): `link:/releases/BASE/{base_release}/base_types.html#_real_data_item_class[Real_data_item^]`
a|

h|*1..1*
|*read_quantity_variable* ( +
subject_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]`, +
name: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]` +
): `link:/releases/BASE/{base_release}/base_types.html#_quantity_data_item_class[Quantity_data_item^]`
a|

h|*1..1*
|*read_coded_term_variable* ( +
subject_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]`, +
name: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]` +
): `link:/releases/BASE/{base_release}/base_types.html#_coded_term_data_item_class[Coded_term_data_item^]`
a|

h|*1..1*
|*read_text_variable* ( +
subject_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]`, +
name: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]` +
): `link:/releases/BASE/{base_release}/base_types.html#_text_data_item_class[Text_data_item^]`
a|

h|*0..1*
|*remove_plan* ( +
subject_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]`, +
plan_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]` +
)
a|

h|*0..1*
|*remove_subject* ( +
subject_id: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^][1]` +
)
a|
|===
