=== PROXY_SERVICE Interface

[cols="^1,3,5"]
|===
h|*Interface*
2+^h|*PROXY_SERVICE*

h|*Description*
2+a|Service that tracks registered subject variables and caches them. Calls to `_register_variable_()` will cause the creation of two things:

* a local cache of time-tagged historical values of the variable;
* an agent or other method of obtaining the variable value from back-end systems.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*register_variable* ( +
subject_id: `String[1]`, +
plan_id: `String[1]`, +
def: `SP_VARIABLE_DEF[1]`, +
currency: `Iso8601_duration[0..1]` +
)
a|Register a new variable for a subject and plan. The variable definition is given by `_def_`. If `_currency_` is specified, it indicates the oldest value acceptable to maintain the validity of the variable.

h|*1..1*
|*read_boolean_variable* ( +
subject_id: `String[1]`, +
name: `String[1]` +
): `Boolean_data_item`
a|

h|*1..1*
|*read_integer_variable* ( +
subject_id: `String[1]`, +
name: `String[1]` +
): `Integer_data_item`
a|

h|*1..1*
|*read_real_variable* ( +
subject_id: `String[1]`, +
name: `String[1]` +
): `Real_data_item`
a|

h|*1..1*
|*read_quantity_variable* ( +
subject_id: `String[1]`, +
name: `String[1]` +
): `Quantity_data_item`
a|

h|*1..1*
|*read_coded_term_variable* ( +
subject_id: `String[1]`, +
name: `String[1]` +
): `Coded_term_data_item`
a|

h|*1..1*
|*read_text_variable* ( +
subject_id: `String[1]`, +
name: `String[1]` +
): `Text_data_item`
a|

h|*0..1*
|*remove_plan* ( +
subject_id: `String[1]`, +
plan_id: `String[1]` +
)
a|

h|*0..1*
|*remove_subject* ( +
subject_id: `String[1]` +
)
a|
|===
