=== TASK_REPEAT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*TASK_REPEAT*

h|*Description*
2+a|Definition of repetition for a Plan Item. The `_repeats_` attribute states the number of repeats. Here, 'repeats' means additional executions, i.e. not counting the original execution. If not set, any number of repeats is allowed. The minimum number of repeats is set by the lower bound of `_repeats_`.

If set, the `_terminate_condition_` attribute defines when repetition should cease, once the minimum number of repeats has occurred according to `_repeats_`. It is expressed in terms of a condition, typically a subject-related variable. It is tested after prior to each new potential execution following the minimum number.

If `_period_` is set, this defines the duration between the start of each iteration at execution time. It has the effect at runtime of adding a `_wait_spec_` with a `TIMELINE_MOMENT` event to each `PLAN_ITEM` copy in the materialised form, i.e. creating the same structure as would have been created if the repetitions had been manually specified.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*repeats*: `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_integer_class[Integer^]>`
a|Range of repetitions. If the lower limit is greater than zero, at least one repeat is required. A range such as 0..3 means up to 3 repeats possible, but not required.

h|*0..1*
|*terminate_condition*: `<<_plan_event_class,PLAN_EVENT>>`
a|States a condition for when repetition should stop. If set, tested prior to each further potential repetition once the minimum number have been executed.

h|*0..1*
|*period*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`
a|Optional period of repetition, i.e. duration between the commencement of each `PLAN_ITEM` clone in the materialised form.
|===
