=== TASK_WAIT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*TASK_WAIT*

h|*Description*
2+a|Object representing time of a Task to be performed in terms of a related event. The `_start_window_` is used to add an 'acceptable delay' time within which the Task should be started with respect to the intended start time. The `_timeout_` attribute can be used for non-deterministic Events.

* clock time: event = `TIMELINE_MOMENT`, `CALENDAR_EVENT`;
* notification-based: event = `MANUAL_NOTIFICATION`, `CALLBACK_NOTIFICATION` or `SYSTEM_NOTIFICATION`;
* task-linked: event = `TASK_TRANSITION`, e.g. 1hr after previous Task done;
* state-linked: event = `STATE_TRIGGER`, e.g. 'when systolic BP > 165'.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*events*: `List<PLAN_EVENT>`
a|One or more events that define the intended point in time. If there are more than one, the implied logical relation is OR, i.e. any event occurring causes the wait state to complete.

h|*0..1*
|*event_relation*: `TEMPORAL_RELATION`
a|Temporal relation to the event of the point or period in time being defined by this Timing Spec.

h|*0..1*
|*timeout*: `TIMER_WAIT`
a|Timeout handler to use if no other Event is received within a certain time.

h|*0..1*
|*next_state*: `TASK_LIFECYCLE`
a|Override for next state to enter on receipt of any Event in `_events_`. Default processing is to enter the `available` state.
|===
