=== TASK_GROUP Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*TASK_GROUP*

h|*Description*
2+a|Grouping structure that defines the graph structure of a Task Plan, replacing node-to-node references.

This allows Task Group to define the execution basis for a collection of Tasks, which may include more Task groups.

The `_execution_type_` attribute defines the mode of execution. If not set, sequential execution is assumed.

If set to `parallel`, the Task Group represents a split/join pair with respect to all contained Tasks and Groups. In this case, `_concurrency_mode_` may be set to control the processing. If it is not set, 'AND' logic is assumed (i.e. `and_all_paths`).

h|*Inherit*
2+|`PLAN_ITEM`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*members*: `List<PLAN_ITEM>`
a|Set of Tasks to perform. Execution order is defined by the `_execution_type_` setting, either sequential or parallel (no order).

h|*0..1*
|*execution_type*: `EXECUTION_TYPE`
a|Basis for executing the Task items contained in this Task Group.

h|*0..1*
|*training_level*: `Integer`
a|An integer value representing the training level for which this Task Plan is designed. A high value corresponds to a lower level of expertise. The default value is zero.

h|*0..1*
|*execution_rules*: `List<EXECUTION_RULE>`
a|Other rules that may control execution over and above the basic sequential / parallel scheme, e.g.

* at least N members must complete for group to complete;
* exit group on first succeeding task.

h|*0..1*
|*concurrency_mode*: `CONCURRENCY_MODE`
a|Mode in which to execute if execution type is parallel.
|===
