=== TASK_LIFECYCLE Enumeration

[cols="^1,3,5"]
|===
h|*Enumeration*
2+^h|*TASK_LIFECYCLE*

h|*Description*
2+a|Enumeration representing possible lifecycle states for a Task lifecycle transition, for example, "not needed".

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|
|planned
a|Task is defined, but not yet available for execution.

h|
|available
a|Task is available for execution by the performer, due to previous Tasks having been performed, preconditions being met, and if there is a time specification on the Task, the current time being at or later than the stated time.

h|
|cancelled
a|Task was cancelled prior to or during execution as not needed for success of the Plan.

Terminal state.

h|
|abandoned
a|Task was aborted due to completion being impossible, i.e. ended prematurely without meeting normal conditions of completion.

Terminal state.

h|
|completed
a|Task was completed in the intended way.

Terminal state.

h|
|suspended
a|Task is suspended, waiting for completion of a handoff or external request.

h|
|underway
a|Task has been commenced or resumed from 'suspend' state.
|===
