=== TASK_WAIT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*TASK_WAIT*

h|*Description*
2+a|Object representing time of an Task to be performed in terms of a related event. The `_delay_` attribute may be used to delay the start time by some amount. The `_start_window_` is used to add an 'acceptable delay' time within which the Task should be start with respect to the intended start time. The `_timeout_` attribute can be used for non-deterministic Events

* clock time: event = `TIMER_EXPIRY`
* event-linked: event = `CALENDAR_EVENT` or `MANUAL_EVENT`, e.g. evening meal, washing, etc;
* task-linked: event = `TASK_TRANSITION`, e.g. 1hr after previous Task done;
* state-linked: event = `STATE_TRIGGER`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*events*: `List<PLAN_EVENT>`
a|Event that defines the intended point in time.

h|*0..1*
|*event_relation*: `TEMPORAL_RELATION`
a|Temporal relation to the event of the point or period in time being defined by this Timing Spec.

h|*0..1*
|*start_window*: `REMINDER`
a|Time window after an initial time during which the action should start. Allows for approximate times to be used operationally.

h|*0..1*
|*timeout*: `TIMER_WAIT`
a|Timeout handler to use if no other Event is received within a certain time.
|===
