=== TASK_ACTION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_TASK_ACTION (abstract)_*

h|*Description*
2+a|Abstract parent of Task Action types, which define the specifics of the work of a Task. All Task Actions may have subject preconditions (i.e. preconditions on the state of the subject) that must be met or overridden before proceeding; costing information; and one or more review data sets to display in the application environment.

Performable Actions have further properties.

h|*Inherit*
2+|`LOCATABLE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*review_dataset*: `List<DATASET_SPEC>`
a|Optional data-set to review prior to / as part of performing Task. This implies a data retrieval from the EHR or other system, which may be specified using a SYSTEM_REQUEST attached to this Task.

h|*0..1*
|*instruction_activity*: `LOCATABLE_REF`
a|Optional reference back to the `ACTIVITY` of an `INSTRUCTION` that generated this `TASK`.

TODO: may be movable to `PERFORMABLE_ACTION`.

h|*0..1*
|*subject_preconditions*: `List<SUBJECT_PRECONDITION>`
a|Condition which must be met for the Task Action to be available to perform in a runtime execution context.

h|*0..1*
|*costing_data*: `TASK_COSTING`
a|Costing data related to this Task item.
|===
