=== TRACKED_VARIABLE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*TRACKED_VARIABLE<T>*

h|*Description*
2+a|Abstraction representing a 'tracked' real-world variable representing a quality of a subject, e.g. patient systolic blood pressure, diabetic status, date of birth etc, whose value is sampled and potentially tracked over time.

The generic parameter is a model type from an accessible model.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*name*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|

h|*0..1*
|*currency*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`
a|If set, maximum age of a real-world snapshot of this variable's value.

h|*0..1*
|*history*: `link:/releases/BASE/{base_release}/foundation_types.html#_hash_class[Hash^]<link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^],<<_value_snapshot_class,VALUE_SNAPSHOT>>>`
a|Local history of values.

h|*0..1*
|*max_history*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`
a|

h|*0..1*
|*time_window*: `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^]>`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*value* (): `T`
a|Retrieve latest value, or null if none.

h|*1..1*
|*value_at_time* ( +
a_time: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^][1]` +
): `T`
a|Return the value from `_history_` that was available at time `_time_`.

h|*1..1*
|*is_available* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Return True if there is a value in `_history_` whose `_time_` is within the duration of `_currency_` of the current moment.

h|*0..1*
|*unavailable_reason* (): `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|If `_is_available_` is False, potentially provide a reason.

h|*1..1*
|*is_tracking* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Return true if tracking (i.e. snapshotting) is occurring, i.e. if `_currency_` is set. False indicates that a single sample is sufficient.
|===
