=== TRACKED_STATE_VARIABLE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*TRACKED_STATE_VARIABLE<T>*

h|*Description*
2+a|A 'tracked' subject variable representing a continuant quality of a subject over time, e.g. patient systolic blood pressure, heart rate etc, whose value is sampled over time.

The generic parameter is a model type from an accessible model.

h|*Inherit*
2+|`<<_state_variable_class,STATE_VARIABLE>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*currency*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`
a|If set, maximum age of a real-world snapshot of this variable's value to be usable or valid.

h|*0..1*
|*max_history*: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*value_at_time* ( +
a_time: `link:/releases/BASE/{base_release}/foundation_types.html#_iso8601_date_time_class[Iso8601_date_time^][1]` +
): `T`
a|Return the value from `_history_` that was available at time `_time_`.

h|*1..1 +
(redefined)*
|*is_available* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Return True if there is a member of `_history_` whose `_time_` is within the duration of `_currency_` of the current moment.
|===
