=== TRACKED_VARIABLE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*TRACKED_VARIABLE*

h|*Description*
2+a|Specialised property that represents a 'tracked variable' within the DLM `input` section. A tracked variable is used to record snapshots of an external variable such as a subject blood pressure.

h|*Inherit*
2+|`link:/releases/LANG/{proc_release}/bmm.html#_bmm_unitary_property_class[BMM_UNITARY_PROPERTY^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*history*: `link:/releases/BASE/{base_release}/foundation_types.html#_hash_class[Hash^]<link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^],<<_value_snapshot_class,VALUE_SNAPSHOT>>>`
a|

h|*0..1*
|*currency*: `link:/releases/BASE/{proc_release}/foundation_types.html#_iso8601_duration_class[Iso8601_duration^]`
a|If set, maximum age of a real-world snapshot of this variable's value.

h|*1..1 +
(redefined)*
|*type*: `link:/releases/LANG/{proc_release}/bmm.html#_bmm_simple_type_class[BMM_SIMPLE_TYPE^]`
a|Declared or inferred static type of the entity.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*range* ( +
a_range: `link:/releases/BASE/{proc_release}/foundation_types.html#_terminology_code_class[Terminology_code^][1]` +
): `link:/releases/LANG/{proc_release}/bmm.html#_bmm_interval_value_class[BMM_INTERVAL_VALUE^]`
a|Function to return the interval of a named range.

h|*1..1*
|*in_range* ( +
a_range: `link:/releases/BASE/{proc_release}/foundation_types.html#_terminology_code_class[Terminology_code^][1]` +
): `link:/releases/BASE/{proc_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Determine if the last read value of the variable is in the named range.

h|*1..1*
|*range_of* (): `link:/releases/BASE/{proc_release}/foundation_types.html#_terminology_code_class[Terminology_code^]`
a|Return the name of the range within which the last read value of the variable resides.
|===
