=== WORK_PLAN Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*WORK_PLAN*

h|*Description*
2+a|Top-level object of any logical work plan. References one or more `TASK_PLANs` that described the work, typically of each performer, although a single `TASK_PLAN` may also have multiple performers.

h|*Inherit*
2+|`AUTHORED_RESOURCE`, `CONTENT_ITEM`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*care_pathway*: `DV_IDENTIFIER`
a|Identifier of care pathway etc, on which this Work Plan is based, if such exists. A 'care pathway' is understood here as a published standard for performing care for a major condition or presenting complaint, e.g. sepsis, MI etc.

It is currently assumed that there is no reliable machine identifier system for care pathways. A `DV_IDENTIFIER` allows things like:

* `issuer = "NICE"`;
* `id = "https://pathways.nice.org.uk/pathways/sepsis"`;
* `type = "NICE Sepsis care pathway"`.

h|*1..1*
|*plans*: `List<UID_BASED_ID>`
a|References to all Task Plans use in this Work Plan. In general, only some of these are top-level Plans.

h|*0..1*
|*care_plan*: `LOCATABLE_REF`
a|Care plan in EHR from which this Work Plan is derived, if any.

h|*0..1*
|*order_list*: `List<LOCATABLE_REF>`
a|Reference list of orders in this Work Plan.

h|*1..1*
|*calendar*: `PLAN_CALENDAR`
a|Global calendar object, containing events fixed in time relevant to the Plan's Tasks, for example appointments.

h|*1..1*
|*timeline*: `PLAN_TIMELINE`
a|Global timeline of Work Plan, on which Tasks with planned times can be listed.

h|*0..1*
|*context*: `PLAN_DATA_CONTEXT`
a|Global Work Plan data context.

h|*0..1*
|*event_wait_states*: `List<EVENT_WAIT>`
a|Reference list of all defined Event Listeners.

h|*0..1*
|*top_level_plans*: `List<TASK_PLAN>`
a|The set of top-level Plans that correspond to the performers and work pathways of this Work Plan.

h|*0..1*
|*indications*: `List<DV_TEXT>`
a|Clinical applicability of this Work Plan to subject of work, e.g. 'acute ischaemic stroke' etc. May be derived from a governing guideline.

h|*1..1 +
(redefined)*
|*description*: `DV_TEXT`
a|Human-understandable description of the Task Plan, which may be specific to the work items and patient.
|===
