= Preface

== Purpose

This document describes a visual modelling language for the openEHR Task Planning Model, known as TP-VML. This is designed to enable visually efficient visual representations of Task Plans to be authored with appropriately configured tools.

The intended audience includes:

* Task Plan and workflow authors;
* Tool vendors.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_task_planning}[openEHR Task Planning Model];

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_tp_vml}.

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the {openehr_technical_list}[technical mailing list], or on the {openehr_jira}/SPECPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel[specifications issue tracker].

== Conformance

Conformance of a data or software artifact to an openEHR Reference Model specification is determined by a formal test of that artifact against the relevant openEHR Implementation Technology Specification(s) (ITSs), such as an IDL interface or an XML-schema. Since ITSs are formal, automated derivations from the Reference Model, ITS conformance indicates RM conformance.

