= Elements

== Composites

=== Plans

[.text-center]
.Plans
image::{diagrams_uri}/TP-VML-plans.svg[id=tp_vml_plans, align="center"]

=== Task Groups

[.text-center]
.Task groups
image::{diagrams_uri}/TP-VML-task_groups.svg[id=tp_vml_task_groups, align="center"]

=== Conditional Structures

[.text-center]
.Conditional structures - CONDITION_GROUP
image::{diagrams_uri}/TP-VML-conditionals_condition.svg[id=tp_vml_conditionals_condition, align="center"]

[.text-center]
.Conditional structures - DECISION_GROUP
image::{diagrams_uri}/TP-VML-conditionals_decision.svg[id=tp_vml_conditionals_decision, align="center"]

[.text-center]
.Conditional structures - EVENT_GROUP
image::{diagrams_uri}/TP-VML-conditionals_event.svg[id=tp_vml_conditionals_event, align="center"]

== Primitives

=== Tasks

[.text-center]
.Tasks
image::{diagrams_uri}/TP-VML-tasks.svg[id=tp_vml_tasks, align="center"]

=== Events

[.text-center]
.Events
image::{diagrams_uri}/TP-VML-events.svg[id=tp_vml_events, align="center", width=70%]

