= Task Planning Model Overview

The following UML diagram shows the `rm.task_planning` package in overview form, showing the constituent packages, `definition`, `materialised`, and `history`. The first of these packages contains the class model for the _definition model_ expression of a Work Plan, i.e. the workflow structure intentionally designed to achive a goal.

The `materialised` package contains the class model of the amterialised form of the definition, which is created prior to its use in execution. The materialised model is presented in outline only, as a way of indicating some of the general features of the materialised form, and is not intended to be normative. (At some point in the future, a skeleton materialised model may be declared normative, based on implementation experience).

The `history` package contains the model of audit events that have occurred to each Task Plan in a Work Plan during execution.

[.text-center]
.rm.task_planning package overview
image::{uml_diagrams_uri}/PROC-task_planning-overview.svg[id=proc_task_planning_overview, align="center"]

The following instance diagram illustrates the relationships among these models for one Task Plan. On the left is a Task Plan definition, consisting of a Task Group and various Defined Actions. Each of these Tasks may have a prototype Entry attached, which represents the intended data of an Action, Observation or other Entry that the Task defines.

In the centre is a materialised Task Plan, which is an execution-time structure used to maintain state for an executing Plan. This structure allows the representation of all state to do with Plan execution, including instances of variables, timing information and so on. The materialised structure is not owned by the definition structure, but rather is created at run time, and points back to its definition via various references. The right hand side of the diagram shows a part of the materialised structure that is currently instantiated within a user-application session.

At the lower right is a Task Plan Execution History, which is a record of all events that were made during the execution of the original Task Plan.

[.text-center]
.Task planning overview
image::{diagrams_uri}/task_planning_overview.svg[id=task_planning_overview, align="center", width=65%]

== Identification and Referencing

With a Task Plan, various elements need to be referenceable at runtime. Tasks and Task Groups are identified via the `_uid_` attribute inherited from `LOCATABLE` via `PLAN_ITEM`, and which is populated with a Guid. References to a Task or Task Group are thus achieved with `UID_BASED_ID` instances carrying a Guid.

== Specifying Time

Generic classes for specifying time formally and in customary form such as 'afternoon' are provided for use in the main model. These are shown bottom right of the above UML diagram: `TIME_SPECIFIER` and descendants.

== Plan Data Context

A Task Plan may contain logical _variable references_ and _expressions_, which are used in various ways within the Plan structure. These are globally collated and tracked at runtime at the Work Plan level, i.e. in common to all Task Plans. To facilitate their definition and computable use, they are fully typed. The following UML diagram illustrates. 

[.text-center]
.Task planning - context values
image::{uml_diagrams_uri}/PROC-task_planning.definition-context.svg[id=proc_task_planning_context, align="center"]

An instance of `PLAN_DATA_CONTEXT` represents the full set of tracked variables and expressions used in a Work Plan, which are either  atomic _variables_ or _expressions_ that reference such variables, respectively represented by the classes `CONTEXT_VARIABLE<T>` and `CONTEXT_EXPRESSION<T>`. These classes and the abstract parent are generic, with the parameter being the formal type of variable or expression.

Variables are typically related to subject state, such as patient vital signs, key demographic characteristics and so on, or the clinical care process, such as the 'time since stroke event', while expressions are used to represent logical expressions such as `systolic_bp - diastolic_bp`, where `systolic_bp` and `diastolic_bp` are defined as single variables. The syntax of expressions is defined by the {openehr_expression}[openEHR Expression language].

Each context variable has a symbolic name (`CONTEXT_VARIABLE._name_`), a type from within the openEHR type system (`EXPR_TYPE_DEF`), and a _populating_request_, which defines how to populate the variable with a System Request, typically an EHR query or similar.

There are two types of variables - 'event' and 'state', which distinguish the update basis. An Event variable is 'watched' by some technical means, and its value is updated whenever it changes. The `CONTINUOUS_EVENT_VARIABLE` specialised type can be used for managing updates of continuous valued variables (i.e. real values) such that changes below a certain threshold, say 2% do not register.

== Class Descriptions

include::{uml_export_dir}/classes/plan_data_context.adoc[]

include::{uml_export_dir}/classes/context_value.adoc[]

include::{uml_export_dir}/classes/context_variable.adoc[]

include::{uml_export_dir}/classes/event_variable.adoc[]

include::{uml_export_dir}/classes/continuous_event_variable.adoc[]

include::{uml_export_dir}/classes/state_variable.adoc[]

include::{uml_export_dir}/classes/context_expression.adoc[]

include::{uml_export_dir}/classes/boolean_context_expression.adoc[]


include::{uml_export_dir}/classes/system_call.adoc[]

include::{uml_export_dir}/classes/task_lifecycle.adoc[]

include::{uml_export_dir}/classes/resume_type.adoc[]

include::{uml_export_dir}/classes/temporal_relation.adoc[]

include::{uml_export_dir}/classes/execution_type.adoc[]


include::{uml_export_dir}/classes/time_specifier.adoc[]

include::{uml_export_dir}/classes/clock_time.adoc[]

include::{uml_export_dir}/classes/calendar_time.adoc[]

include::{uml_export_dir}/classes/customary_time.adoc[]
