== Task Group Structure

The set of Tasks in a Task Plan is represented within a containment structure created using instances of the `TASK_GROUP` class, which has three key attributes. Execution of a Group is primarily controlled by the `_execution_type_` and `_concurrency_mode_` attributes, which respectively indicate sequential or parallel processing, and for the latter case, various modes of `and` and `or` parallel processing logic (described in the next section), common to workflow formalisms. For more exotic situations, the `_execution_rules_` attribute can be used.

`TASK_GROUP` also has a `_training_level_` attribute which enables different visibility of Sub-Plans to users with different experience levels. This is described more fully <<_training_level,below>>.

The Task Group construct enables two important ways to relate Tasks together:

* as a _module_ of work consisting of a series of Tasks, achieved by a Task Group with `_execution_type_ = sequential`;
* as a set of possible or mandatory _concurrent threads of work_, achieved by a Task Group with `_execution_type_ = parallel`.

=== Sequential Task Groups

A sequential Task Group corresponds to a single thread of processing at execution time, in which each of the Tasks becomes available to the worker (i.e. Task Plan's `_principal_performer_`) _in order_, and according to the specific conditions associated with each Task. The following illustrates a sequential Task Group in TP-VML. Note that although there is visually an end-group icon (right hand end), there is no separate class or instance in the model - both the start-group and end-group icons visually represent the `TASK_GROUP` as a logical container.

[.text-center]
.Sequential Task Group
image::{diagrams_uri}/task_group_sequential.svg[id=task_group_sequential, align="center", width=45%]

=== Parallel Task Groups and Concurrency

The parallel Task Group represents a different degree of complexity, since it enables concurrent threads of work at execution time. In terms of YAWL and Petri net workflow theory, a parallel Task Group corresponds to paired _split_ and _join_ points. The following illustrates a parallel Task Group in TP-VML. The multi-point shape of the exit and entry elements is intended to convey the idea of multiple possible branches (the limitation of 3 points is purely visual, semantically, any number of branches is supported).

[.text-center]
.Parallel Task Group
image::{diagrams_uri}/task_group_parallel.svg[id=task_group_parallel, align="center", width=25%]

The first difference between a parallel Group and a sequential one is that when a parallel Group is arrived at in the control flow, once any wait state is satisfied, the first Task in _all of the outgoing branches_ is made `available`. Subsequent execution behaviour depends on the type of split and join logic (i.e. AND, OR, XOR, or other) which is represented by the attribute `TASK_GROUP._concurrency_mode_`, whose possible values indicate to the execution engine three things:

* how many branches may be commenced;
* how commencing a branches affects other branches;
* under what conditions to consider the group has completed.

Here, the notion of 'completion' corresponds to the `completed` state in the Task lifecycle state machine described earlier, inferred from the completion states of the items in the branches. The detail of how Task Group lifecycle state is aggregated from contained items is described in detail in <<Aggregate Lifecycle State>>. Here we describe only the logic determining the `completed` state, for the sake of simplicity.

The AND case is the simplest, since there is no conditional processing - all paths must be followed. An AND Group essentially represents work that should be performed, but for which the ordering is more relaxed than for a strict sequential Group.

The XOR case represents a 1/N choice, and is understood in this specification as representing the _intent_ that only one path can sensibly be followed, usually because the branches are mutually exclusive alternatives in reality. Consequently, in execution, an XOR Group is processed such that as soon as one branch is chosen by a performer transitioning a Task from the `available` state, _the first Task in all remaining branches is transitioned to_ `cancelled`, effectively cancelling the non-chosen branches. In this case completion is also trivial to determine. 

However the OR case is more complicated. A minimal interpretation of 'OR' logic is that as soon as one branch in the Group completes, the Group is considered `completed`, and no more Tasks from other branches are available to perform. A maximal interpretation is that Group completion is achieved only when every path commenced completes. The model represents these two cases explicitly, via the values `or_first_completed` and `or_all_started` respectively of `TASK_GROUP._concurrency_mode_`.

The following table summarises the semantics of the four concurrency modes.

[cols="2,1,1,3,3", options="header"]
|===
|Concurrency mode    |TP-VML |Logic |Split +
                                     behaviour |Join +
                                                behaviour

|`and_all_paths`     
a|image::{diagrams_uri}/task_group_parallel_and.svg[id=task_group_parallel_and]
|AND                |All branches are followed. |Group completes when all branches complete.

|`xor_one_path`     
a|image::{diagrams_uri}/task_group_parallel_xor.svg[id=task_group_parallel_xor]
|XOR                |Only one branch can be started; once a branch is commenced, the first Task in remaining branches is transitioned to `cancelled`. |Group completes when the started branch completes; equivalent to a sequential Group, once a branch is chosen.

|`or_all_started`    
a|image::{diagrams_uri}/task_group_parallel_or_all.svg[id=task_group_parallel_or_all]
|partial AND        |One or more branches may be commence. |The Group is complete when all branches commenced have completed; equivalent to an AND consisting of all commenced branches.

|`or_first_completed`
a|image::{diagrams_uri}/task_group_parallel_or_first.svg[id=task_group_parallel_or_first]
|OR                 |One or more branches may be commenced. |The Group is complete when one branch completes.

|===

The parallel / concurrent semantics attached to the Task Group do not indicate anything about decisional processing, i.e. the conditions that might be used to choose outgoing paths from the split point represented by a Task Group in the XOR and OR logic cases. Consequently, the choice of path(s) to follow in the parallel case is determined _by the performer, not the system_. In order to specify conditions on paths, the conditional subtypes <<_decision_structures, described below>> are used.

=== Hierarchical Nesting

Task Groups of sequential and parallel types may be mixed in a hierarchical fashion. One structure is such that the overall work of a Task Plan is defined as a sequential Group in which some members are a parallel Group, as shown below.

[.text-center]
.Nested Task grouping - sequential structure
image::{diagrams_uri}/task_grouping.svg[id=task_grouping, align="center", width=75%]

Similarly, the outermost Group may be parallel, with the work being defined as sections of sequential work situated within a parallel Task Group, as shown below.

[.text-center]
.Nested Task grouping - parallel chains
image::{diagrams_uri}/task_grouping2.svg[id=task_grouping2, align="center", width=75%]

=== Generic Execution-time Semantics

The combination of the Task Group / Task hierachical pattern, which implicitly defines the graph structure of the 'normal flow' of a Task Plan, and the generic control attributes defined on `TASK` and its descendant types enable a significant amount of execution-time Plan processing to be implemented independently of any specific Task semantics.

=== Well-formedness

A significant consequence of the Task Group construct in the TP model is that each Task Group forms a sub-network within its container, where a _network_ is understood in the graph theory sense of a directed graph with a start `s` and terminal node `t`, containing paths from `s` to `t` n which all member elements are found. This holds for descendant types of `TASK_GROUP`, including the <<_decision_structures, Decision Structures>> described below. This is a more limited form of connectivity than allowed in YAWL or BPMN, which do not require matched split and join points.

=== Training Level

One challenge with creating Task Plan definitions is the level of detail to use, with respect to the variable level of skill of different performers. For a senior nurse, a briefer version of the Plan would be preferable with actions such as 'set up IV with catheter' being a single atom, whereas a trainee may need to see a more detailed set of sub-tasks. 

To enable a single Plan to be used in both ways, the concept of 'training level' is included in the model, on the `TASK_GROUP` class. This enables any Group of Tasks to be marked as having a specific training level, where a higher number corresponds to less experience. At execution time, the training level of the allocated performer can be obtained, and then used in comparison to the training level indicated on each Group (including the top-level Group of the whole Plan). If the user training level is higher, then the Group may be shown only as a single step (using its `_description_`, inherited from `PLAN_ITEM`); otherwise it may be shown as the set of sub-steps. This provides a simple way for the same Plan to be presented in different forms matching different performer experience levels.

The default value of `_training_level_` is 0.

=== Class Definitions

include::{uml_export_dir}/classes/task_group.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/execution_type.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/concurrency_mode.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/execution_rule.adoc[leveloffset=+1]
