= Task Planning Model

== Overview

The following UML diagram shows the `rm.task_planning` package in overview form, with the essential classes, inheritance and compositional relationships. The class `WORK_PLAN` is a descendant of `CONTENT_ITEM`, which makes it a type of content that may occur in a `COMPOSITION`. Compositions used for this purpose have their `_category_` attribute set to the openEHR coded term `|Task Plan|`. This enables Task Plans to be committed to the openEHR EHR if desired.

A `WORK_PLAN` is the outermost container for one or more `TASK_PLANs` that refer to each other in some way, as well as the meta-data documenting the plan.

Structurally, a `TASK_PLAN` has a `_definition_` (blue classes) consisting of `TASK_GROUP` and `TASK`. The work of a Task is defined in the hierarchy of `TASK_ACTION` types.

At clinical execution time, the materialsed form of the Plan is represented by `M_XXX` classes, which are instantiated when the plan is activated (central orange classes).

A `TASK_PLAN` may also have an `_execution_history_` (gold classes at bottom), which acts as a record of events that have occurred to the Task Plan during execution.

[.text-center]
.rm.task_planning package overview
image::{uml_export_dir}/diagrams/PROC-task_planning-overview.svg[id=proc_task_planning_overview, align="center"]

The key structural relationships are shown in the following instance diagram. On the left is a Task Plan definition, consisting of a Task Group and various Defined Actions. Each of these Tasks may have a prototype Entry attached, which represents the intended data of an Action, Observation or other Entry that the Task defines.

In the centre is a materialised Task Plan, which is an execution-time structure used to maintain state for an executing Plan (achieved by the `M_PLAN_ITEM._definition_` association). This structure allows the recording of all state to do with Task execution, including instances of variables, timing information and so on. The materialised structure is not owned by the definition structure, but rather is created at run time, and points back to its definition (_owner_ and _definition_ links). The right hand side shows a part of the materialised structure that is currently instantiated within a user-application session.

At the lower right is a Task Execution History, which is a record of all events that were made during the execution of the original Task Plan.

[.text-center]
.Task planning overview
image::diagrams/task_planning_overview.svg[id=task_planning_overview, align="center", width=75%]

== Identification and Referencing

With a Task Plan, various elements need to be referenceable at runtime. Tasks and Task Groups are identified via the `_uid_` attribute inherited from `LOCATABLE` via `PLAN_ITEM`, and which is populated with a Guid. References to a Task or Task Group are thus achieved with `UID_BASED_ID` instances carrying a Guid.

== Plan Data Context

A Task Plan may contain logical _variable references_ and _expressions_, which are used in various ways within the Plan structure. These are globally collated and tracked at runtime at the Work Plan level, i.e. in common to all Task Plans. To facilitate their definition and computable use, they are fully typed. The following UML diagram illustrates. The type `PLAN_DATA_CONTEXT` represents the full set of tracked variables and expressions used in the Plan.

[.text-center]
.Task planning - context values
image::{uml_export_dir}/diagrams/PROC-task_planning.definition-context.svg[id=proc_task_planning_context, align="center"]

Variables are typically related to subject state, such as patient vital signs, key demographic characteristics and so on, or the clinical care process, such as the 'time since stroke event'. In order to allow expressions to use symbolic variables such as `is_female` or `stroke_time` within logical expressions, a way of defining each variable is required. This is provided by the `CONTEXT_VARIABLE` type.

Each context variable has a symbolic name (`CONTEXT_VARIABLE._name_`), a type from within the openEHR type system (`EXPR_TYPE_DEF`), and a _populating_request_, which defines how to populate the variable with a System Request, typically an EHR query or similar.

[.tbd]
TBD: to be continued; see also {openehr_expression}[openEHR Expression language].

== Class Descriptions

include::{uml_export_dir}/classes/plan_data_context.adoc[]

include::{uml_export_dir}/classes/context_value.adoc[]

include::{uml_export_dir}/classes/context_variable.adoc[]

include::{uml_export_dir}/classes/event_variable.adoc[]

include::{uml_export_dir}/classes/state_variable.adoc[]

include::{uml_export_dir}/classes/context_expression.adoc[]


include::{uml_export_dir}/classes/system_call.adoc[]

include::{uml_export_dir}/classes/task_lifecycle.adoc[]

include::{uml_export_dir}/classes/resume_type.adoc[]

include::{uml_export_dir}/classes/temporal_relation.adoc[]
