== Data-sets and Application Interaction

In order for performers to execute Task Groups and individual Tasks with a Plan, specific data must often be reviewed to enable the performer to know how to proceed. This is generally the case for Tasks that involve administering drugs to a patient, where the dose depends on one or more variables relating to the patient state, such as ECG data, INR, heart rate etc.

The following UML diagram shows the data-set related classes in detail.

[.text-center]
.proc.task_planning.definition model overview
image::{uml_diagrams_uri}/PROC-task_planning.definition-dataset.svg[id=proc_definition_dataset, align="center"]

A 'data-set' in openEHR is a template, normally displayed as a form within an application. Either a template or form identifier (or both) maybe be used to specify a data-set. A _review data-set_ may be specified on any Plan Item (i.e. Task Group of Task, of any kind) via the attribute `PLAN_ITEM._review_dataset_`, in order to signal to the runtime system to request the display of data at the start of that part of the Plan.

Related to this is the `_capture_dataset_` attribute of the `PERFORMABLE_TASK` type, which enables the association of a dataset or form for inputting data with a performable Task.

[.tbd]
TBD: describe how this relates to the data set(s) of `PERFORMABLE_ACTION._prototype_` .

=== Class Definitions

include::{uml_export_dir}/classes/dataset_spec.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/capture_dataset_spec.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/review_dataset_spec.adoc[leveloffset=+1]
