= Preface

== Purpose

This specification of the openEHR Task Planning facility addresses requirements in the area of automated clinical process support in which some form of granular planning of clinical work is required. The central concept is that of a _plan_ (or set of plans) designed to achieve a _goal_ and that relate to an _active biological subject_.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* The open source healthcare community;
* Solution vendors;
* Medical informaticians and clinicians interested in health information.
* Health data managers.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview^].

Related documents include:

* The {openehr_tp_vml}[Task Planning Visual Modelling Language (TP-VML)^];
* The {openehr_rm_ehr}[openEHR EHR Information Model^];

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_proc_latest_task_planning}[{openehr_proc_latest_task_planning}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_process_forum}[process specifications forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant {openehr_its_component}[openEHR Implementation Technology Specification(s) (ITSs)^], such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.

