== General Task Semantics

=== Dispatchable and Performable Tasks

Tasks are represented by the `TASK` class whose two concrete sub-types distinguish the two basic flavours of Task, namely _dispatchable_ and _performable_. `TASK` is a generic (i.e. templated) class, whose generic parameter is constrained to the type `TASK_ACTION`, the latter of whose subtypes defined the particular kinds of Tasks available. 

The `DISPATCHABLE_TASK<T>` class has two attributes to do with managing context change and callback. The `_wait_` flag indicates whether the current Task waits (i.e. blocks) while the dispatched work is performed, or whether it continues on asynchronously. The first constitutes a context switch, the second a context fork. The `_callback_` attribute attaches a special kind of Event wait state that is triggered on receipt of a callback. How callbacks function in detail is <<_callbacks,described below>>.

There are some key differences between the two kinds of Task as shown in the following table.

[cols="1,3,3", options="header"]
|===
|Task Type      |Description                                                                   |Lifecycle state

|_Performable_  |Task performed by the current performer.                                      |Advanced by actions of performer (real world actor)
|_Dispatchable_ |A Task whose work is dispatched for execution to another performer or system. |_wait_ = `True`: Advanced by receipt of callback notification +
                                                                                                _wait_ = `False`: Automatically advanced to `completed`
|===

=== Class Definitions

include::{uml_export_dir}/classes/task.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/dispatchable_task.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/performable_task.adoc[leveloffset=+1]
