= Proxy Objects

== Overview

From a data perspective, the set of features defined in an SPO will relate to a particular use. For example, the properties for a leukaemia patient are likely to include `white_cell_count`, `platelets` and so on, while a DPO for ante-natal use will contain obstetric properties. A core set of SPO features for any patient would include clinical basics such as date of birth, sex, and typical vital signs. In general, the collection of features in an SPO will be a somewhat arbitrary 'slice' of all possible variables and events characterising a real-world entity. 

The following illustrates two SPOs, one a specialisation of the other.

[.text-center]
.Abstract proxy
image::{diagrams_uri}/conceptual_proxy.svg[id=conceptual_proxy, align="center"]

== Variable Naming

[.tbd]
TBD: basic question of variable like 'Apgar 5min heartrate' - represent in a structure, and reference like `apgar_result.5min.heart_rate`, or just use flat pre-coord approach: `apgar_result_5min_heart_rate`? Structuring probably makes authoring easier.