= Preface

== Purpose

This document specifies the openEHR Subject Proxy Model, that may be used with the {openehr_decision_language}[openEHR Decision Language^] and/or with the {openehr_task_planning}[openEHR Task Planning^] model.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* Solution vendors.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview^].

Related documents include:

* The {openehr_task_planning}[openEHR Task Planning specification^];
* The {openehr_cds_gdl}[Guideline Definition Language (GDL)^].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_proc_latest_subject_proxy}[{openehr_proc_latest_subject_proxy}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an openEHR specification is determined by a formal test of that artifact against the relevant {openehr_its_component}[openEHR Implementation Technology Specification(s) (ITSs)^], such as an IDL interface or an XML-schema. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.

