include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Thomas Beale, Ars Semantica (UK); openEHR Foundation Management Board.

=== Contributors

This specification benefited from formal and informal input from the openEHR and wider health informatics community. The openEHR Foundation would like to recognise the following people for their contributions.

* Borut Fabjan, Program Manager, Marand, Slovenia
* Matija Kejžar, Marand, Slovenia
* Eugeny Leonov, Solit Clouds, Moscow, Russia
* Bjørn Næss, DIPS, Norway

=== Support

The work reported in this specification has been funded by the following organisations:

* City of Moscow, Russia
* DIPS, Norway
* Marand d.o.o., Slovenia
* Ars Semantica, UK

=== Trademarks

* 'openEHR' is a trademark of the openEHR Foundation.
* 'OMG' is a trademark of the Object Management Group.
== Conformance

Conformance of a data or software artifact to an openEHR Reference Model specification is determined by a formal test of that artifact against the relevant openEHR Implementation Technology Specification(s) (ITSs), such as an IDL interface or an XML-schema. Since ITSs are formal, automated derivations from the Reference Model, ITS conformance indicates RM conformance.


:sectnums!:

include::partial$amendment_record.adoc[]
